#!/bin/bash

echo "🚀 Manual FTP Upload Script"
echo "=========================="
echo ""
echo "📁 File: dashboard-create-content-unified.php"
echo "🌐 Server: ftp.11klassniki.ru"
echo ""
echo "Please manually upload the file using an FTP client with these credentials:"
echo ""
echo "Host: ftp.11klassniki.ru"
echo "Username: 11klassnikiru_0"
echo "Password: Tg)LyR)qC3"
echo "Directory: /11klassnikiru"
echo ""
echo "The file contains the image preview feature with:"
echo "✅ Real-time preview on file selection"
echo "✅ Support for PNG, JPG, JPEG, GIF, WebP"
echo "✅ Remove button to clear selection"
echo "✅ Responsive preview (max-height: 300px)"
echo ""
echo "After upload, test at: https://11klassniki.ru/create/news"